blog/urls.py
from django.conf.urls import url
from django.contrib.auth.decorators import login_required
from django.views.generic import TemplateView
from . import views
from blog.views import CreatePostView, ShowPostView, IndexView, UserUpdateView, MyPostView, \
UpdatePostView, MyPublishPostView, MyUnPublishPostView, MyArchivePostView, DeletePostView, \
MakePostPublishView, MakePostUnpublishView, MakePostArchieveView, NotificationView, \
CommentOnMyPostView, DeleteCommentView, BecomeBloggerView, CreateCommentView

urlpatterns = [
  url(r'^$',IndexView.as_view(), name = 'index'),
  url(r'^createpost$',login_required(CreatePostView.as_view()), name = 'createpost'),
  url(r'^success/$', login_required(TemplateView.as_view(template_name="blog/success.html")), name = 'success'),
  url(r'^update$',login_required(UserUpdateView.as_view()), name = 'update'),
  url(r'^mypost$',login_required(MyPostView.as_view()), name = 'mypost'),
  url(r'^updatepost/(?P<slug>[\w\-]+)/$',login_required(UpdatePostView.as_view()), name='updatepost'),
  url(r'^mypublishpost/$', login_required(MyPublishPostView.as_view()), name='mypublishpost'),
  url(r'^myunpublishpost/$', login_required(MyUnPublishPostView.as_view()), name='myunpublishpost'),
  url(r'^myarchivepost/$', login_required(MyArchivePostView.as_view()), name='myarchivepost'),
  url(r'^publishpost/(?P<slug>[\w\-]+)/$',login_required(MakePostPublishView.as_view()), name='publishpost'),
  url(r'^unpublishpost/(?P<slug>[\w\-]+)/$',login_required(MakePostUnpublishView.as_view()), name='unpublishpost'),
  url(r'^archivepost/(?P<slug>[\w\-]+)/$', login_required(MakePostArchieveView.as_view()), name='archivepost'),
  url(r'^notifications/$', NotificationView.as_view(), name='notifications'),
  url(r'^viewpost/(?P<slug>[\w\-]+)/$', ShowPostView.as_view(), name='viewpost'),
  url(r'^commentonmypost/(?P<slug>[\w\-]+)/$', CommentOnMyPostView.as_view(), name='commentonmypost'),
  url(r'^deletepost/(?P<slug>[\w\-]+)/$',login_required(DeletePostView.as_view()), name='deletepost'),
  url(r'^deletecomment/(?P<c_id>[0-9]+)/$', login_required(DeleteCommentView.as_view()), name='deletecomment'),
  url(r'^becomeblogger/$', BecomeBloggerView.as_view(), name='becomeblogger'),
  url(r'^createcomment/(?P<slug>[\w\-]+)/$', login_required(CreateCommentView.as_view()), name='createcomment'),

  
  url(r'^viewpost/(?P<slug>[\w\-]+)/likepost/$', views.like_post_view, name='likepost'),
  url(r'^viewpost/(?P<slug>[\w\-]+)/likecomment/(?P<c_id>[0-9]+)/$', views.like_comment_view, name='likecomment'),



  url(r'^paginateupper/$', views.ajax_upper_paginate_view, name='paginateupper'),
  url(r'^paginatemiddle/$', views.ajax_middle_paginate_view, name='paginatemiddle'),
  url(r'^paginatelower/$', views.ajax_lower_paginate_view, name='paginatelower'),
  url(r'^searchpost/$', views.search_post_view, name='searchpost'),
  url(r'^searchpostajax/$', views.search_post_ajax_view, name='searchpostajax'),
  
  # url(r'^showallcomments/(?P<c_id>[0-9]+)/$', views.show_all_comments_view, name='showallcomment'),
]

myblog/urls.py
from django.conf.urls import url,include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include('blog.urls', namespace='blog')),
    url(r'^accounts/', include('allauth.urls')),
    url(r'^ckeditor/', include('ckeditor_uploader.urls')),
    ]

blog/models.py
from __future__ import unicode_literals

from django.db import models
from django.contrib.auth.models import User
from django.db.models.signals import post_save
from django.dispatch import receiver
from django.utils import timezone
from ckeditor.fields import RichTextField
from django.template.defaultfilters import slugify
from django.urls import reverse


class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    blogger = models.BooleanField(default=False)
    request = models.BooleanField(default=False)
    notify =  models.BooleanField(default=False)
    def __str__(self):
        return self.user.username


@receiver(post_save, sender=User)
def create_user_profile(sender, instance, created, **kwargs):
    if created:
        Profile.objects.create(user=instance)

@receiver(post_save, sender=User)
def save_user_profile(sender, instance, **kwargs):
    instance.profile.save()


class Post(models.Model):
    user = models.ForeignKey(User,null=True,blank=True, on_delete=models.CASCADE)
    post = models.CharField(max_length=100,verbose_name='Title',unique=True)
    likes = models.IntegerField(default=0)
    description = RichTextField(verbose_name='Description')
    publish = models.BooleanField(default=False,verbose_name='Publish')
    published = models.DateTimeField(default=timezone.now)
    created = models.DateTimeField(default=timezone.now)
    archive = models.BooleanField(default=False)
    archive_date = models.DateTimeField(null=True,blank=True)
    views = models.IntegerField(default=0)
    slug = models.SlugField(blank=True)
  

    def __str__(self):
        return self.post

    def save(self, *args, **kwargs):
        if not self.id:
            self.slug = slugify(self.post) #Or whatever you want the slug to use
        super(Post, self).save(*args, **kwargs)

    def get_absolute_url(self):
        return reverse('blog:viewpost', kwargs = {'slug' : self.slug})


class Comment(models.Model):
    posts = models.ForeignKey(Post,null=True,blank=True, on_delete=models.CASCADE)
    comment = models.CharField(max_length=100)
    author = models.ForeignKey(User, null=True, blank=True)
    likes = models.IntegerField(default=0)
    notifications = models.CharField(max_length=50,blank=True)
    com_created = models.DateTimeField(auto_now=True)
    approve = models.BooleanField(default=True)

    def __str__(self):
        return self.comment

    class Meta:
        ordering = ['-com_created']

class PostLike(models.Model):
    posts = models.ForeignKey(Post,null=True,blank=True, on_delete=models.CASCADE)
    user = models.ForeignKey(User, null=True, blank=True)
    ip = models.CharField(max_length=20)

class CommentLike(models.Model):
    comments = models.ForeignKey(Comment,null=True,blank=True, on_delete=models.CASCADE)
    user = models.ForeignKey(User, null=True, blank=True)
    ip = models.CharField(max_length=20)

class Search(models.Model):
    search = models.CharField(max_length=30)

blog/forms.py
from django import forms
from blog.models import Post,Comment,Profile,Search
from django.contrib.auth.models import User

from django.utils import timezone
from ckeditor.fields import RichTextField
from datetimewidget.widgets import DateTimeWidget


class CreatePostForm(forms.ModelForm):
  # published = forms.DateTimeField(widget=DateTimeWidget( bootstrap_version=3),initial=timezone.now)
  class Meta:
    model = Post
    fields = ('post','description', 'publish', 'published',)

    
class UpdateUserForm(forms.ModelForm):
  class Meta:
    model = User
    fields = ('first_name','last_name','email')

class UpdatePostForm(forms.ModelForm):
  class Meta:
    model = Post
    fields = ('post','description','publish')

class CommentForm(forms.ModelForm):
  class Meta:
    model = Comment
    fields = ('comment',)

class NotificationForm(forms.ModelForm):
  class Meta:
    model = Profile
    fields = ('notify',)

class SearchForm(forms.ModelForm):
  class Meta:
    model = Search
    fields = ('search',)

blog/views.py
import datetime
import json
from datetime import date

from django.views import View
from django.views.generic.detail import DetailView
from django.views.generic.list import ListView
from django.views.generic.edit import UpdateView, DeleteView, FormView

from django.conf import settings
from django.shortcuts import render, get_object_or_404, Http404
from django.http import HttpResponse, HttpResponseRedirect
from django.template import loader
from django.urls import reverse
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.contrib.auth.models import User
from django.utils import timezone
from django.contrib.auth.decorators import login_required
from django.utils.module_loading import import_module
from ipware.ip import get_ip
from django.contrib import messages
from django.db.models import Q
from django.core.mail import EmailMessage
from django.core import serializers
from django.template.loader import render_to_string
from django.shortcuts import render_to_response
from django.core.exceptions import PermissionDenied
from django.core.urlresolvers import reverse_lazy

from .models import Post, Profile, Comment, PostLike, CommentLike, Search
from .forms import CreatePostForm, UpdateUserForm, UpdatePostForm, CommentForm, \
NotificationForm, SearchForm
from .mixins import PaginationMixin

  
class IndexView(ListView):
    model = Post
    template_name = 'blog/homepage.html'
    form_class = SearchForm

    def get_context_data(self, **kwargs):
        context = super(IndexView, self).get_context_data(**kwargs)
        
        context['latest_posts'] = Post.objects.filter(publish=True, published__lte=datetime.datetime.now(), archive=False).order_by('-published')
        paginator = Paginator(context['latest_posts'], 3)
        page = self.request.GET.get('page')
      
        try:
            context['latest_posts'] = paginator.page(page)
        except PageNotAnInteger:
            context['latest_posts'] = paginator.page(1)
        except EmptyPage:
            context['latest_posts'] = paginator.page(paginator.num_pages)

        context['latest_posts_likes']=Post.objects.filter(publish=True, published__lte=datetime.datetime.now(), archive=False).order_by('-likes')
        paginator = Paginator(context['latest_posts_likes'], 3)
        page = self.request.GET.get('page')
      
        try:
            context['latest_posts_likes'] = paginator.page(page)
        except PageNotAnInteger:
            context['latest_posts_likes'] = paginator.page(1)
        except EmptyPage:
            context['latest_posts_likes'] = paginator.page(paginator.num_pages)


        context['latest_posts_views']=Post.objects.filter(publish=True, published__lte=datetime.datetime.now(), archive=False).order_by('-views')
        paginator = Paginator(context['latest_posts_views'], 3)
        page = self.request.GET.get('page')
      
        try:
            context['latest_posts_views'] = paginator.page(page)
        except PageNotAnInteger:
            context['latest_posts_views'] = paginator.page(1)
        except EmptyPage:
            context['latest_posts_views'] = paginator.page(paginator.num_pages)

        context['searchform'] = self.form_class
        return context


class CreatePostView(View):
    form_class = CreatePostForm
    template_name = 'blog/createpost.html'


    def get(self, request):
        form = self.form_class()
        searchform = SearchForm()
        return render(request, self.template_name, {
            "form" : form, 
            "searchform" : searchform 
            })

    def post(self, request):
        form = self.form_class(request.POST)
        searchform = SearchForm()
        if form.is_valid():
            f=form.save()
            f.user = request.user
            f.save()
            return HttpResponseRedirect(reverse('blog:success'))

        return render(request, self.template_name, {
            "form" : form, 
            "searchform" : searchform 
            })


class UserUpdateView(UpdateView):
    form_class = UpdateUserForm
    template_name = 'blog/updateinfo.html'
    success_url = reverse_lazy('blog:index') 

    def get_object(self):
        return User.objects.get(id=self.request.user.id)



class MyPostView(PaginationMixin, ListView):
    template_name = 'blog/mypost.html'

    def get_context_data(self, **kwargs):
        context = super(MyPostView, self).get_context_data(**kwargs)
        context['cur_date'] = timezone.now
        context['title'] = 'MyPost'
        return context

    def get_queryset(self):
        return self.request.user.post_set.filter(archive=False).order_by('-created')



class UpdatePostView(UpdateView):
    form_class = UpdatePostForm
    template_name = 'blog/updatepost.html'
    success_url = reverse_lazy('blog:mypost')

    def get_object(self, queryset=None):
        return Post.objects.get(slug=self.kwargs['slug'])

    def dispatch(self, request, *args, **kwargs):
        self.obj = self.get_object()
        if self.obj.user != request.user:
            raise PermissionDenied
        return super(UpdatePostView, self).dispatch(request, *args, **kwargs)


class DeletePostView(View):
    def get(self, request, slug):
        post = get_object_or_404(Post, slug=slug)
        post.delete()
        return HttpResponseRedirect(request.META.get('HTTP_REFERER'))


class MakePostPublishView(View):
    def get(self, request, *args, **kwargs):
        post = get_object_or_404(Post, slug=kwargs['slug'])
        post.publish = True
        post.published = timezone.now() 
        post.save()
        return HttpResponseRedirect(request.META.get('HTTP_REFERER'))


class MakePostUnpublishView(View):
    def get(self, request, *args, **kwargs):
        post = get_object_or_404(Post, slug=kwargs['slug'])
        post.publish = False
        post.save()
        return HttpResponseRedirect(request.META.get('HTTP_REFERER'))

  
class CreateCommentView(FormView):
    template_name = 'blog/createcomment.html'
    form_class = CommentForm

    def get_context_data(self, **kwargs):
        context = super(CreateCommentView, self).get_context_data(**kwargs)
        context['instance'] = Post.objects.get(slug = self.kwargs['slug'])
        return context

    def form_valid(self, form):
        instance = get_object_or_404(Post, slug=self.kwargs['slug'])
        if instance.user.profile.notify:
            user = User.objects.get(id=self.request.user.id)
            sender = instance.user.email  
            email = EmailMessage('Notification For Comment', "User "+user.username+" Commented on Your Post " , to=[sender])
            email.send()
        f = form.save(commit=False)
        f.posts = instance
        f.author = self.request.user
        f.save()
        return super(CreateCommentView, self).form_valid(form)

    def get_success_url(self):
        return reverse('blog:viewpost', kwargs={'slug': self.kwargs['slug']})


def like_post_view(request, slug):
    post = get_object_or_404(Post, slug=slug)
    if request.user.is_authenticated():
        if PostLike.objects.filter(user=request.user, posts = post).exists():
            data = {"message":'You Already Like it',"likes":post.likes}
            return HttpResponse(json.dumps(data), content_type="application/json")
        else:
            ip = get_ip(request)
            postlike = PostLike.objects.create(ip=ip)
            postlike.user=request.user
            postlike.posts = post
            postlike.save()
            post.likes = post.likes +1
            post.save()
            data = {'message':'You like it' ,"likes":post.likes}
            return HttpResponse(json.dumps(data), content_type="application/json")
    else:
        data = {"message":'You Need to Login First!!!',"likes":post.likes}
        return HttpResponse(json.dumps(data), content_type="application/json")

def like_comment_view(request, slug,c_id):
    comment = get_object_or_404(Comment, id=c_id) 

    if request.user.is_authenticated():
        if CommentLike.objects.filter(user=request.user, comments = comment).exists():
            data = {"message":'You Already Like it',"likes":comment.likes}
            return HttpResponse(json.dumps(data), content_type="application/json")
        else:
            ip = get_ip(request)
            commentlike = CommentLike.objects.create(ip=ip)
            commentlike.user=request.user
            commentlike.comments = comment
            commentlike.save()
            comment.likes = comment.likes +1
            comment.save()
            data = {'message':'You like it' ,"likes":comment.likes}
            return HttpResponse(json.dumps(data), content_type="application/json")
    else:
        data = {"message":'You Need to Login First!!!',"likes":comment.likes}
        return HttpResponse(json.dumps(data), content_type="application/json")

 
class CommentOnMyPostView(ListView):
    template_name = 'blog/mypostcomment.html'
    paginate_by = 3

    def get_context_data(self, **kwargs):
        context = super(CommentOnMyPostView, self).get_context_data(**kwargs)
        context['post'] = Post.objects.get(slug=self.kwargs['slug'])
        return context

    def get_queryset(self):
        return Post.objects.get(slug=self.kwargs['slug']).comment_set.all()

class DeleteCommentView(View):

    def get(self,request, c_id):
        comment = get_object_or_404(Comment, id=c_id)
        comment.delete()
        return HttpResponseRedirect(request.META.get('HTTP_REFERER'))


class MyPublishPostView(PaginationMixin, ListView):
    template_name = 'blog/mypost.html'

    def get_queryset(self):
        return self.request.user.post_set.filter(
            publish = True, 
            published__lte=datetime.datetime.now(), 
            archive=False
            ).order_by('-created')

    def get_context_data(self, **kwargs):
        context = super(MyPublishPostView, self).get_context_data(**kwargs)
        context['cur_date'] = timezone.now

blog/templates/blog/createpost.html
 {% extends 'blog/base.html' %}
{% load widget_tweaks %}
{% load crispy_forms_tags %}

{% block title %}Create Post{% endblock %}

{% block page_plugin %}
  

{% endblock %}


{% block content %}
  <div class="row">
    <div class="col-sm-4 col-md-2 col-lg-2"></div>
    <div class="col-sm-4 col-md-8 col-lg-8">
    
    
      <form name = "form" action = "{% url 'blog:createpost' %}" 
      id="myform" method = "POST" >
        {% csrf_token %}
        <!-- {% for hidden in form.hidden_fields %}
          {{ hidden }}
        {% endfor %}

        {% for field in form.visible_fields %}
          <div class="form-group">
            <label for="{{ field.id_for_label }}">{{ field.label }}</label>
            {{ field|add_class:'form-control' }}
            {% for error in field.errors %}
              <span class="help-block">{{ error }}</span>
            {% endfor %}
          </div>
        {% endfor %} -->
        {{form|crispy}}

        <input type="submit" name="submit" value="Create Post">
      </form>
    </div>
    <div class="col-sm-4 col-md-2 col-lg-2"></div>
   
    <!-- <form name="form">
      {% for field in form %}
         <div class="md-form-group float-label">
             <label>{{ field.label_tag }}</label>
             {% render_field field class="md-input" %}
         </div>

      {% endfor %}
      <input type="submit" name="submit" value="Create Post">
    </form> -->
   
  </div>
  {% endblock %}
</body>
  {% block page_js %}
    
    <link rel="stylesheet" href="https://jqueryvalidation.org/files/demo/site-demos.css">
    <script src="https://cdn.jsdelivr.net/jquery.validation/1.15.0/jquery.validate.min.js"></script>
    <script src="https://cdn.jsdelivr.net/jquery.validation/1.15.0/additional-methods.min.js"></script>

    <link rel="stylesheet" href="//code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css">
    <!-- <link rel="stylesheet" href="/resources/demos/style.css"> -->
    <script src="https://code.jquery.com/jquery-1.12.4.js"></script>
    <script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>
    <script src="http://ajax.aspnetcdn.com/ajax/jquery.validate/1.11.1/jquery.validate.min.js"></script>


   
  


   <script type="text/javascript">
     

    CKEDITOR.replace( 'id_description' );
      // just for the demos, avoids form submit
      $( function() {
        $( "#id_published" ).datepicker({minDate: 0});

      });
      // $("#myform").submit( function(e) {
      //       var messageLength = CKEDITOR.instances['id_description'].getData().replace(/<[^>]*>/gi, '').length;
      //       if( !messageLength ) {
      //           alert( 'Please enter a value in texteditor' );
      //           e.preventDefault();
      //       }
      //   });


      $("#myform" ).validate({
        rules: {
          post: {
            required: true,
            // unique: true,
          },
          description:{
            required: function(textarea) {
          CKEDITOR.instances['id_description'].updateElement(); // update textarea
          var editorcontent = id_description.value.replace(/<[^>]*>/gi, ''); // strip tags
          return editorcontent.length === 0;
          } 
          }        
        },
        messages:{
         post :{
            required : "Please enter a Suitable Title",
            // unique: "Please enter a unique title"
         },
         description : {
            required : "Please enter Post Description"
         }
        }
      });
    </script>
            
          
  <!-- </script> -->

  
  {% endblock %}

blog/templates/blog/myarchivepost.html
{% extends 'blog/base.html' %}
{% block title %}{{title}}{% endblock %}

{% block content %}
    {% if request.user.profile.blogger == True %}
        <ul>
            {% for post in post_list %}
                <div class="post"><a href="{{ post.get_absolute_url }}">{{ post.post|safe}}</a></div>
                <br>
            {% endfor %}
        </ul>

        {% if page_obj.has_other_pages %}
            {% if page_obj.has_previous %}
                <a href="?page={{ latest_post.previous_page_number }}">&laquo;</a>
            {% else %}
                <span>&laquo;</span>
            {% endif %}
            {% for i in page_obj.paginator.page_range %}
                {% if latest_post.number == i %}
                    <span>{{ i }} <span >(current)</span></span>
                {% else %}
                    <a href="?page={{ i }}">{{ i }}</a>
                {% endif %}
            {% endfor %}
            {% if page_obj.has_next %}
                <a href="?page={{ page_obj.next_page_number }}">&raquo;</a>
            {% else %}
                <span>&raquo;</span>
            {% endif %}
        {% endif %}
    {% endif %}
  
{% endblock %}

blog/templates/blog/mypost.html
{% extends 'blog/base.html' %}

{% block title %}{{title}}{% endblock %}

{% block content %}
    {% if request.user.profile.blogger == True %}
        <ul>
            {% for post in post_list %}
                <div class="post"><a href="{{ post.get_absolute_url }}">{{ post.post|safe}}</a></div>
                <a href="{% url 'blog:updatepost' post.slug %}"><span class="glyphicon glyphicon-edit"></span> Update</a>
                <a href="{% url 'blog:deletepost' post.slug %}"><span class="glyphicon glyphicon-trash"></span> Delete</a>
                {% if post.publish == False or post.published > cur_date %}
                    <a href="{% url 'blog:publishpost' post.slug %}"><span class="glyphicon glyphicon-check"></span> Publish</a>
                {% else %}
                    <a href="{% url 'blog:unpublishpost' post.slug %}"><span class="glyphicon glyphicon-unchecked"></span>UnPublish</a>
                {% endif %}
                <a href="{% url 'blog:commentonmypost' post.slug %}"><span class="glyphicon glyphicon-th-list"></span> Comments</a>
                <a href="{% url 'blog:archivepost' post.slug %}"><span class="glyphicon glyphicon-briefcase"></span> Archive</a>
            {% endfor %}
        </ul>

        {% if is_paginated %}
            <ul class="pagination">
                {% if page_obj.has_previous %}
                    <li><a href="?page={{ page_obj.previous_page_number }}">&laquo;</a></li>
                {% else %}
                    <li class="disabled"><span>&laquo;</span></li>
                {% endif %}
                {% for i in paginator.page_range %}
                    {% if page_obj.number == i %}
                        <li class="active"><span>{{ i }} <span class="sr-only">(current)</span></span></li>
                    {% else %}
                        <li><a href="?page={{ i }}">{{ i }}</a></li>
                    {% endif %}
                {% endfor %}
                {% if page_obj.has_next %}
                    <li><a href="?page={{ page_obj.next_page_number }}">&raquo;</a></li>
                {% else %}
                    <li class="disabled"><span>&raquo;</span></li>
                {% endif %}
            </ul>
        {% endif %}
    {% endif %}

{% endblock %}

blog/templates/blog/mypostcomment.html
{% extends 'blog/base.html' %}
{% load staticfiles %}
{% block title %}Comments{% endblock %}

{% block content %}
  
    <div class="post">{{ post.post|safe }}</div>
    Written by <strong>{{ post.user}}</strong>
    at {{ post.created }}
    <br>
    <a href="{% url 'blog:createcomment' post.slug%}"><span class="glyphicon glyphicon-comment"></span> Comment</a>
    <br>
    {% if comment_list %}
        {% for latcomment in comment_list %}
            <div class="comment">
            <strong style="color:  #5b331c ">{{latcomment.author.username }}</strong><br>
            {{latcomment.comment}}<br>
           
            <a href="{% url 'blog:deletecomment' latcomment.id%}"><span class="glyphicon glyphicon-remove"></span>Remove</a>
            </div>
            <br>
        {% endfor %}
        
        <br>

        {% if page_obj.has_other_pages %}
          
            {% if page_obj.has_previous %}
                <a href="?page={{ page_obj.previous_page_number }}">&laquo;</a>
            {% else %}
                <span>&laquo;</span>
            {% endif %}
            {% for i in page_obj.paginator.page_range %}
                {% if page_obj.number == i %}
                    <span>{{ i }} <span >(current)</span></span>
                {% else %}
                    <a href="?page={{ i }}">{{ i }}</a>
                {% endif %}
            {% endfor %}
            {% if page_obj.has_next %}
                <a href="?page={{ page_obj.next_page_number }}">&raquo;</a>
            {% else %}
                <span>&raquo;</span>
            {% endif %}
          
        {% endif %}
    {% else %}
        <div class="comment">No Comments Posted Yet.</div>
    {% endif %}
  
{% endblock %}

blog/templates/blog/updateinfo.html
{% extends 'blog/base.html' %}
{% load crispy_forms_tags %}

<!DOCTYPE html>
<html>
<head>
  {% block title %}Update Info{% endblock %}
</head>
<body>
  {% block content %}
  <div>
     
    <form name = "form" action = "{% url 'blog:update' %}" 
      id="myform" method = "POST" >
        {% csrf_token %}
        {{ form|crispy}}
        <input type="submit" name="submit" value="Update">
    </form>
  {% endblock %}
</body>
</html>

blog/templates/blog/viewpost.html
{% extends 'blog/base.html' %}
{% load crispy_forms_tags %}


{% block title %}View Post {% endblock %}
  


{% block content %}
<div class="name"> <b>{{post.user}}</b> </div>
  <div>
    <div class="post">{{ post.post|safe }}</div><br>
    <div class="description">{{ post.description|safe }}</div>
  </div>
  <button type="button" class="btn btn-primary like-btn bt" id="like" data-post_id="{{post.id}}"><span class="glyphicon glyphicon-thumbs-up " ></span>{{post.likes}} Like</button>  
    <a href="{% url 'blog:createcomment' post.slug %}"><span class="glyphicon glyphicon-comment"></span> Comment</a>
  
    
     <br>
    {% if comments %}
      <div class="infinite-container">
      {% for comment in comments %}
      
        <div class="comment">
        <div class="name">
        {{comment.author}}
        </div>
        {{ comment.comment }}
        <br>
        <button type="button" class="btn btn-primary like-btn_comment bt" id="like" data-comment_id="{{comment.id}}"><span class="glyphicon glyphicon-thumbs-up " ></span>{{comment.likes}} Like</button>
        </div>
        <br>
      {% endfor %}
      </div>

      {% if comments.has_next %}
        <a class="infinite-more-link" href="?page={{ comments.next_page_number }}">More</a>
      {% endif %}

      <div class="loading" style="display: none;">
      Loading...
      </div>
    {% else %}
      <div class="comment">No Comments Posted Yet.</div>
    {% endif %}
{% endblock %}

{% block page_js %}

<script type="text/javascript">
    var current_obj = false;
    $(document).on('click', '.like-btn', function(e){
      e.preventDefault();
      
      var post_id = $(this).data('post_id');
      current_obj = $(this);
      $.ajax({
        type: "GET",

        url: 'likepost/',
        // data : {'post_id' : parseInt(post_id)},
        success:function(response) {
          current_obj.html("<span class='glyphicon glyphicon-thumbs-up'></span>"+response.likes+" Likes")
          swal(response.message)  
        },
        error:function(response) {
        
        }
      });
    })

    $(document).on('click', '.like-btn_comment', function(e){
      e.preventDefault();
      
      var comment_id = $(this).data('comment_id');
      current_obj = $(this);
      $.ajax({
        type: "GET",

        url: 'likecomment/'+comment_id+'',
        // data : {'post_id' : parseInt(post_id)},
        success:function(response) {
          current_obj.html("<span class='glyphicon glyphicon-thumbs-up'></span>"+response.likes+" Likes")
          swal(response.message)  
        },
        error:function(response) {
        
        }
      });
    })

   
</script>

{% endblock %}